<template><Teleport to="body"><div v-if="open" class="drawer-backdrop" @click.self="$emit('close')"><aside class="drawer" role="dialog" aria-modal="true" :aria-labelledby="titleId"><div class="drawer-handle" aria-hidden="true"></div><header class="drawer-header"><div><span class="eyebrow">{{ eyebrow }}</span><h3 :id="titleId" class="drawer-title">{{ title }}</h3></div><button class="drawer-close" type="button" aria-label="Tutup" @click="$emit('close')"><X aria-hidden="true" /></button></header><div class="drawer-content"><slot /></div></aside></div></Teleport></template>
<script setup>
import { X } from '@lucide/vue';
defineProps({open:Boolean,eyebrow:{type:String,required:true},title:{type:String,required:true},titleId:{type:String,default:'planner-drawer-title'}});defineEmits(['close']);
</script>
<style scoped>
.drawer-backdrop{position:fixed;inset:0;z-index:1000;display:flex;justify-content:flex-end;background:rgba(26,0,30,.28);backdrop-filter:blur(2px);animation:drawerFade .2s ease}.drawer{display:flex;width:min(440px,100vw);height:100dvh;flex-direction:column;background:#fff;animation:drawerFromRight .25s ease}.drawer-handle{display:none}.drawer-header{display:flex;min-height:86px;padding:20px 22px;align-items:center;justify-content:space-between;gap:16px;border-bottom:1px solid #d4ccd4}.eyebrow{display:block;margin:0 0 3px;color:#240029;font-family:'JetBrains Mono',monospace;font-size:9px;font-weight:700;line-height:1.2;letter-spacing:.1em;text-transform:uppercase}.drawer-title{margin:0;color:#240029;font-family:Inter,system-ui,sans-serif;font-size:28px;font-weight:700;line-height:1.25}.drawer-close{display:inline-flex;width:36px;height:36px;align-items:center;justify-content:center;border:0;border-radius:6px;background:transparent;color:#240029;cursor:pointer}.drawer-close:hover{background:#fff1f8;color:#df37a7}.drawer-close svg{width:15px}.drawer-content{display:contents}@keyframes drawerFade{from{opacity:0}}@keyframes drawerFromRight{from{transform:translateX(100%)}}@keyframes drawerFromBottom{from{transform:translateY(100%)}}
@media(max-width:767px){.drawer-backdrop{align-items:flex-end}.drawer{width:100%;height:auto;max-height:92dvh;border-radius:20px 20px 0 0;animation:drawerFromBottom .25s ease}.drawer-handle{display:block;width:40px;height:4px;margin:9px auto 0;border-radius:99px;background:#d4ccd4}.drawer-header{min-height:68px;padding:10px 16px 13px}.drawer-close{width:44px;height:44px}}
@media(prefers-reduced-motion:reduce){.drawer-backdrop,.drawer{animation:none!important}}
</style>
